export const GAMEPLAY = {
    debug: {
        showCollisionBoxes: false,
    },
    player: {
        speed: 500,
        maxHealth: 100,
        scaleFactor: 0.75,
        abilities: ['Boomerang', 'Gun'],
        levelStart: 1,
        xpStart: 0,
        xpToNextLevelStart: 40,
        xpGrowth: 1.35,
        body: { shape: 'rectangle', widthFactor: 0.7 },
        healthBar: {
            width: 42,
            minWidth: 28,
            height: 6,
            offsetY: 10,
            fillColor: 0x4caf50,
            backgroundColor: 0x163017,
            borderColor: 0x0c1b0c,
        },
    },
    abilities: {
        gun: {
            count: 3,
            speed: 200,
            cooldown: 300,
            maxInGame: 100,
            despawnBuffer: 160,
            spread: 0.1,
            damage: 20,
            scaleFactor: 1,
            pierce: 1,
            body: { shape: 'circle', radiusFactor: 0.7 },
        },
        boomerang: {
            count: 1,
            cooldown: 1800,
               shotDelayMs: 140,
            // Lifetime only: speed controls travel rate, duration controls active time.
            duration: 180000,
            speed: 250,
            range: 400,
            spread: 0.8,
            curveAmplitude: 70,
            roseK: 5,
            spinSpeed: 0.025,
            damage: 26,
            scaleFactor: 2,
            maxInGame: 99,
            body: { shape: 'circle', radiusFactor: 0.75 },
        },
    },
    enemies: {
        maxInGame: 100,
        despawnBuffer: 360,
        damageIntervalMs: 250,
        healthBar: {
            minWidth: 24,
            height: 5,
            offsetY: 8,
            fillColor: 0xc0392b,
            backgroundColor: 0x2e0f0f,
            borderColor: 0x200909,
        },
        enemyTypes: {
            enemy1: {
                speed: 90,
                maxHealth: 30,
                damage: 8,
                scaleFactor: -2,
                xpYield: 5,
                body: { shape: 'circle' },
            },
            enemy2: {
                speed: 70,
                maxHealth: 50,
                damage: 12,
                scaleFactor: -2,
                xpYield: 10,
                body: { shape: 'circle' },
            },
            enemy3: {
                speed: 55,
                maxHealth: 80,
                damage: 16,
                scaleFactor: -2,
                xpYield: 20,
                body: { shape: 'circle' },
            },
        },
    },
    spawner: {
        spawnMargin: 100,
        timeline: [
            {
                startAt: 0,
                endAt: 70,
                ratePerSecond: 0.9,
                countPerSpawn: 1,
                enemyPool: ['enemy1'],
            },
            {
                startAt: 60,
                endAt: 130,
                ratePerSecond: 1.2,
                countPerSpawn: 1,
                enemyPool: ['enemy1', 'enemy2'],
            },
            {
                startAt: 120,
                endAt: 190,
                ratePerSecond: 1.5,
                countPerSpawn: 2,
                enemyPool: ['enemy1', 'enemy2'],
            },
            {
                startAt: 190,
                endAt: 99999,
                ratePerSecond: 1.8,
                countPerSpawn: 2,
                enemyPool: ['enemy1', 'enemy2', 'enemy3'],
            },
        ],
    },
};
